In [35]:
import pandas as pd  # For data manipulation
import numpy as np  # For numerical operations

In [36]:
# Load the Dataset
df=pd.read_csv("Amazon-Products.csv")

In [37]:
# To verify the Dataset
# Check First few rows
df.head(180)

,Unnamed: 0,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
0,0,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/31UISB90sY...,https://www.amazon.in/Lloyd-Inverter-Convertib...,4.2,"2,255","₹32,999","₹58,990"
1,1,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Convertible-Anti-Viru...,4.2,"2,948","₹46,490","₹75,990"
2,2,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Inverter-Convertible-...,4.2,"1,206","₹34,490","₹61,990"
3,3,LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Convertible-Anti-Viru...,4.0,69,"₹37,990","₹68,990"
4,4,Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/41lrtqXPiW...,https://www.amazon.in/Carrier-Inverter-Split-C...,4.1,630,"₹34,490","₹67,790"
...,...,...,...,...,...,...,...,...,...,...
175,175,"Daikin 2.02 Ton 4 Star, Inverter Split AC (Cop...",appliances,Air Conditioners,https://m.media-amazon.com/images/I/41H61ZFlBH...,https://www.amazon.in/Daikin-Inverter-Copper-F...,3.4,31,"₹64,990","₹86,800"
176,176,Carrier 1 Ton 3 Star Fixed Speed Window AC(Cop...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/717wB+IneG...,https://www.amazon.in/Carrier-Density-Filtrati...,4.0,1,"₹28,990","₹39,090"
177,177,Hisense 1.0 Ton 5 Star Inverter Split AC (Copp...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51h87m-hf-...,https://www.amazon.in/Hisense-Inverter-Copper-...,3.9,192,"₹32,000","₹45,990"
178,178,Daikin 1.8 Ton 5 Star Inverter Split AC (Coppe...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/418VQew9c-...,https://www.amazon.in/Daikin-Inverter-Copper-F...,4.6,40,"₹69,979","₹92,200"
179,179,Blue Star 1.5 Ton 3 Star Inverter Window AC (C...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/71HYJBEQ7t...,https://www.amazon.in/Blue-Star-Compressor-Tec...,NaN,NaN,"₹35,990","₹45,000"

In [38]:
# To Check dataset info (columns, data types, missing values)
df.info()
# For checking basic statistics
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 551585 entries, 0 to 551584
Data columns (total 10 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Unnamed: 0      551585 non-null  int64
 1   name            551585 non-null  object
 2   main_category   551585 non-null  object
 3   sub_category    551585 non-null  object
 4   image           551585 non-null  object
 5   link            551585 non-null  object
 6   ratings         375791 non-null  object
 7   no_of_ratings   375791 non-null  object
 8   discount_price  490422 non-null  object
 9   actual_price    533772 non-null  object
dtypes: int64(1), object(9)
memory usage: 42.1+ MB

          Unnamed: 0
count  551585.000000
mean     7006.200471
std      5740.835523
min         0.000000
25%      1550.000000
50%      5933.000000
75%     11482.000000
max     19199.000000

## 📌 Key Observations

### 🗑️ Unnecessary Column:
- `Unnamed: 0` is just an index and can be dropped.

### 🔄 Data Type Issues:
- `ratings`, `no_of_ratings`, `discount_price`, and `actual_price` should be numerical but are stored as objects (strings).

### ⚠️ Missing Values:
- `ratings` & `no_of_ratings` → **31.8% missing**
- `discount_price` → **11.1% missing**
- `actual_price` → **3.2% missing**

In [39]:
# To handle all the observed issues 
#Drop the Unnamed Column
df.drop(columns=['Unnamed: 0'], inplace=True)

In [40]:
# Checking again to veryfy that Unnamed column has been dropped or not
df.head()

,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
0,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/31UISB90sY...,https://www.amazon.in/Lloyd-Inverter-Convertib...,4.2,"2,255","₹32,999","₹58,990"
1,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Convertible-Anti-Viru...,4.2,"2,948","₹46,490","₹75,990"
2,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Inverter-Convertible-...,4.2,"1,206","₹34,490","₹61,990"
3,LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Convertible-Anti-Viru...,4.0,69,"₹37,990","₹68,990"
4,Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/41lrtqXPiW...,https://www.amazon.in/Carrier-Inverter-Split-C...,4.1,630,"₹34,490","₹67,790"

In [41]:
#Rupee sign is persent with prices that can cause an error furthur so first remove it 
df['discount_price'] = df['discount_price'].str.replace('₹','',regex=True)
df['actual_price'] = df['actual_price'].str.replace('₹','',regex=True)

# Remove commas from the 'discount_price' column to ensure it can be converted to a numerical format correctly
df['discount_price'] = df['discount_price'].str.replace(',','',regex=True)
df['actual_price'] = df['actual_price'].str.replace(',','',regex=True)

df.head(181)

,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
0,Lloyd 1.5 Ton 3 Star Inverter Split Ac (5 In 1...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/31UISB90sY...,https://www.amazon.in/Lloyd-Inverter-Convertib...,4.2,"2,255",32999,58990
1,LG 1.5 Ton 5 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Convertible-Anti-Viru...,4.2,"2,948",46490,75990
2,LG 1 Ton 4 Star Ai Dual Inverter Split Ac (Cop...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Inverter-Convertible-...,4.2,"1,206",34490,61990
3,LG 1.5 Ton 3 Star AI DUAL Inverter Split AC (C...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51JFb7FctD...,https://www.amazon.in/LG-Convertible-Anti-Viru...,4.0,69,37990,68990
4,Carrier 1.5 Ton 3 Star Inverter Split AC (Copp...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/41lrtqXPiW...,https://www.amazon.in/Carrier-Inverter-Split-C...,4.1,630,34490,67790
...,...,...,...,...,...,...,...,...,...
176,Carrier 1 Ton 3 Star Fixed Speed Window AC(Cop...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/717wB+IneG...,https://www.amazon.in/Carrier-Density-Filtrati...,4.0,1,28990,39090
177,Hisense 1.0 Ton 5 Star Inverter Split AC (Copp...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51h87m-hf-...,https://www.amazon.in/Hisense-Inverter-Copper-...,3.9,192,32000,45990
178,Daikin 1.8 Ton 5 Star Inverter Split AC (Coppe...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/418VQew9c-...,https://www.amazon.in/Daikin-Inverter-Copper-F...,4.6,40,69979,92200
179,Blue Star 1.5 Ton 3 Star Inverter Window AC (C...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/71HYJBEQ7t...,https://www.amazon.in/Blue-Star-Compressor-Tec...,NaN,NaN,35990,45000
180,"Hitachi 1 Ton 3 Star Window AC (Copper, Dust F...",appliances,Air Conditioners,https://m.media-amazon.com/images/I/7139ds6Ypu...,https://www.amazon.in/Hitachi-Window-Copper-Fi...,4.1,101,NaN,NaN

In [44]:
# Now to handle Data Type issue
# Convert ratings to float (ratings usually have decimal values)
df['ratings'] = pd.to_numeric(df['ratings'], errors='coerce').astype(float)
# Convert no_of_ratings, discount_price, and actual_price to integers & handling not a number values with memory optimization
df['no_of_ratings'] = pd.to_numeric(df['no_of_ratings'],errors='coerce').fillna(0).astype(np.int32)
df['discount_price'] = pd.to_numeric(df['discount_price'],errors='coerce').fillna(0).astype(np.int32)
df['actual_price'] = pd.to_numeric(df['actual_price'],errors='coerce').fillna(0).astype(np.int32)

In [45]:
# Verify the changes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 551585 entries, 0 to 551584
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   name            551585 non-null  object
 1   main_category   551585 non-null  object
 2   sub_category    551585 non-null  object
 3   image           551585 non-null  object
 4   link            551585 non-null  object
 5   ratings         369558 non-null  float64
 6   no_of_ratings   551585 non-null  int32
 7   discount_price  551585 non-null  int32
 8   actual_price    551585 non-null  int32
dtypes: float64(1), int32(3), object(5)
memory usage: 31.6+ MB

In [46]:
#After sorting this issue next 
#Checking for the outliers in different-different columns
#Checking for negative or extreme values in pricing
print("Min Discount Price:", df['discount_price'].min())
print("Max Discount Price:",df['discount_price'].max())
print("Min Actual Price:",df['actual_price'].min())
print("Max Actual Price:",df['actual_price'].max())
# Checking for unreal ratings
print("Min Rating:",df['ratings'].min())
print("Max Rating:",df['ratings'].max())

Min Discount Price: 0
Max Discount Price: 1249990
Min Actual Price: 0
Max Actual Price: 2147483647
Min Rating: 1.0
Max Rating: 5.0

#### **Pricing Analysis**
- **Minimum Discount Price:** 0  
- **Maximum Discount Price:** 1,249,990 (Unrealistically high)
- **Minimum Actual Price:** 0  (Unrealistically)
- **Maximum Actual Price:** 9900000000 (Unrealistically high)

#### **Ratings Analysis**
- **Minimum Rating:** 1.0  
- **Maximum Rating:** 5.0 (Within expected range)

 **Observations:**  
- The **maximum actual price** & **Maximum Discount Price:** appears suspiciously high, potentially an outlier.
- The **Minimum Actual Price** is 0 that's

In [23]:
# Set a threshold for extreme prices
extreme_actual_price = df[df['actual_price'] > 1000000]
extreme_discount_price = df[df['discount_price'] > 500000]

# Display the count of extreme values
print("Number of extreme actual prices:", extreme_actual_price.shape[0])
print("Number of extreme discount prices:", extreme_discount_price.shape[0])

Number of extreme actual prices: 7
Number of extreme discount prices: 1

In [24]:
# Display some extreme actual price values
print("Extreme Actual Price Products:")
display(extreme_actual_price[['name', 'actual_price', 'discount_price']].head(10))

# Display some extreme discount price values
print("Extreme Discount Price Products:")
display(extreme_discount_price[['name', 'actual_price', 'discount_price']].head(10))
#verify the prices

Extreme Actual Price Products:

,name,actual_price,discount_price
194625,"Marutivilla Insect Killer, Mosquito Killer Lig...",9.900000e+09,589.0
311949,USPTO डायमंड वन स्टोन D Colour Genuine 3 Carat...,1.200000e+06,406009.0
334263,USPTO डायमंड वन स्टोन D Colour Genuine 3 Carat...,1.200000e+06,406009.0
390319,USPTO डायमंड वन स्टोन D Colour Genuine 3 Carat...,1.200000e+06,406009.0
390351,USPTO डायमंड वन स्टोन D Colour Genuine 3 Carat...,1.200000e+06,406009.0
402750,Clovia Women's Activewear Ankle Length Printed...,6.108299e+07,688.0
498818,Samsung 214 cm (85 inches) 8K Ultra HD Smart N...,1.594900e+06,1249990.0

Extreme Discount Price Products:

,name,actual_price,discount_price
498818,Samsung 214 cm (85 inches) 8K Ultra HD Smart N...,1594900.0,1249990.0

In [27]:
#Fix the incorrect discount price for the Samsung TV
#The actual price is legitimate, but the discount price has an extra zero (1249990 instead of 124999).
df.loc[df['name'].str.contains("Samsung 214 cm", case=False, na=False), 'discount_price'] = 124999

# Remove products with unrealistic actual prices
# The "Marutivilla Insect Killer" and "USPTO Diamond" products have incorrect pricing, so we remove them.
df = df[~df['name'].isin([
    "Marutivilla Insect Killer, Mosquito Killer Lig...",
    "USPTO डायमंड वन स्टोन D Colour Genuine 3 Carat..."
])]

In [29]:
#Verify the fixes
print("Min Discount Price:", df['discount_price'].min())
print("Max Discount Price:",df['discount_price'].max())
print("Min Actual Price:",df['actual_price'].min())
print("Max Actual Price:",df['actual_price'].max())

Min Discount Price: 0.0
Max Discount Price: 499999.0
Min Actual Price: 0.0
Max Actual Price: 9900000000.0

In [34]:
zero_price_products = df[(df['actual_price'] == 0) & (df['discount_price'] == 0)]
print(f"Number of products with both actual price and discount price as 0: {len(zero_price_products)}")
print(zero_price_products.shape[0])  # Display first 10 rows

Number of products with both actual price and discount price as 0: 17815
17815

In [31]:
from IPython.display import display

# Select products where both actual_price and discount_price are zero
zero_price_products = df[(df['actual_price'] == 0) & (df['discount_price'] == 0)]

# Display first 20 rows in tabular format
display(zero_price_products.head(20))

,name,main_category,sub_category,image,link,ratings,no_of_ratings,discount_price,actual_price
76,LG 1.5 Ton 3 Star Hot & Cold DUAL Inverter Spl...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/51hbo8yQ1E...,https://www.amazon.in/LG-Inverter-Convertible-...,4.0,265,0.0,0.0
100,Hitachi 1.5 Ton 5 Star Inverter Split AC (Copp...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/41AY1pk5oR...,https://www.amazon.in/Hitachi-Inverter-Copper-...,3.8,748,0.0,0.0
114,Panasonic 1.5 Ton 4 Star Wi-Fi Twin-Cool Inver...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/41Edvsb7Gh...,https://www.amazon.in/Panasonic-Conditioner-An...,4.5,195,0.0,0.0
144,Daikin 1.5 Ton 4 Star Hot & Cold Heat Pump Inv...,appliances,Air Conditioners,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Daikin-Inverter-Conditio...,3.7,27,0.0,0.0
146,LG 1.5 Ton 5 Star AI DUAL Inverter Wi-Fi Split...,appliances,Air Conditioners,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/LG-Inverter-Convertible-...,4.7,34,0.0,0.0
170,Blue Star 2 Tr 3 Star Fixed Speed Split AC (Co...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/21WQrs98j1...,https://www.amazon.in/Blue-Star-Fixed-Copper-F...,NaN,0,0.0,0.0
180,"Hitachi 1 Ton 3 Star Window AC (Copper, Dust F...",appliances,Air Conditioners,https://m.media-amazon.com/images/I/7139ds6Ypu...,https://www.amazon.in/Hitachi-Window-Copper-Fi...,4.1,101,0.0,0.0
181,Daikin 1.5 Ton 5 Star Dust Filter Window AC (C...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/7125Imt+0z...,https://www.amazon.in/Daikin-1-5-Ton-Star-Wind...,4.1,96,0.0,0.0
196,"Godrej 1 Ton 3 Star Inverter Split AC (Copper,...",appliances,Air Conditioners,https://m.media-amazon.com/images/I/31lenJuVeA...,https://www.amazon.in/Godrej-Inverter-Copper-A...,3.8,51,0.0,0.0
200,"Panasonic 1.5 Ton 3 Star Window AC (Copper, PM...",appliances,Air Conditioners,https://m.media-amazon.com/images/I/61E911ntaK...,https://www.amazon.in/Panasonic-Window-Copper-...,4.2,567,0.0,0.0
206,Daikin 1.5 Ton 3 Star Dust Filter Window AC (C...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/61Kn2QYI1a...,https://www.amazon.in/Daikin-1-5-Ton-Star-Wind...,3.9,62,0.0,0.0
214,LG 1.5 Ton 5 Star Wi-Fi Inverter Split AC (Cop...,appliances,Air Conditioners,https://m.media-amazon.com/images/I/511CwCjVTF...,https://www.amazon.in/LG-Inverter-Convertible-...,4.4,769,0.0,0.0
218,Whirlpool 1.5 Ton 5 Star Inverter Split AC (Co...,appliances,Air Conditioners,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Whirlpool-1-5T-SUPREMECO...,2.9,10,0.0,0.0
221,Lloyd Havells 1.5 Ton 3 Star Window Ac (Copper...,appliances,Air Conditioners,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Lloyd-Window-Copper-Filt...,4.2,329,0.0,0.0
228,"Voltas Adjustable Inverter AC, 1.5 Ton, 3 Star...",appliances,Air Conditioners,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Voltas-Adjustable-Invert...,NaN,0,0.0,0.0
238,Carrier Emperia CXI Wifi 1.5 Ton 5 Star Invert...,appliances,Air Conditioners,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Carrier-Emperia-CXI-Cond...,NaN,0,0.0,0.0
239,Panasonic 2 Ton Hot and Cold Wi-Fi Inverter 3 ...,appliances,Air Conditioners,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Panasonic-Inverter-Coppe...,3.3,5,0.0,0.0
240,"Haier 1.5 Ton 3 Star Antibacterial Coating, Du...",appliances,Air Conditioners,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Haier-Split-Copper-HSU18...,4.0,302,0.0,0.0
251,Daikin 1.5 Ton 5 Star Inverter Split AC (Coppe...,appliances,Air Conditioners,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Daikin-Inverter-Copper-F...,4.2,12,0.0,0.0
252,Panasonic 2.2 Ton Inverter 3 Star Split Smart ...,appliances,Air Conditioners,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/PANASONIC-CS-CU-QU26YKY-...,5.0,2,0.0,0.0